onehand: Fix compilation errors and fwd port to Q
* mService is renamed to mWmService from Ie5788db7f2e823c7d5b64c7ce6eaade1c19c4dcd

* mSurfaceSize removed and setSize() renamed to setBufferSize() from I88bd1452d6b3b3009e73e26986027d6a5a9efebc

* getHandle() is no longer supported from I80da54d92989ec0afe9fcdde324847f0de0c5083
Fixes: frameworks/base/services/core/java/com/android/server/wm/DisplayContent.java:4852: error: incompatible types: IBinder cannot be converted to SurfaceControl
        transaction.reparent(surface, mOneHandOverlayLayer.getHandle());

BUGS:
 - Resizing the display is not smooth
 - Dragging the window to the left/right causes an unexpected artefact where the backgroud does not get cleared on the black empty area

Change-Id: Ic887a7f37bfe49f8aa34861a9b5d2a6ac663ef4e